[workspace]
members = [
    "contracts/my_contract",
    "pallets/cross-chain",
    "node",
    "runtime"
    # Add other members if any
]

# Make sure there are no invalid or unnecessary dependencies listed
[workspace.dependencies]
